services:
  quarkus-app:
    image: wendelsegadilha/quarkus-app:v1
    container_name: quarkus-app
    environment:
      - QUARKUS_CLIENT_HTTP=host.docker.internal
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_HOST=db
      - QUARKUS_DATASOURCE_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: db_quarkus
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quarkus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus_quarkus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_quarkus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
    postgres-data: