quarkus.rest-client.via-cep-api.url=https://viaceplalalal.com.br

quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:postgres}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:postgres}
quarkus.datasource.reactive.url=postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5432}/quarkus
quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.scripts.generation=create
#quarkus.hibernate-orm.scripts.generation.create-target=target/generated.sql

quarkus.micrometer.export.prometheus.path=/metrics